source-dir: $source
state-file: $state
overlay-mode: false
fast-comparison: true
use-local-state: true
use-remote-state: false
state-indent: 2
threads: 1
command-workdir: 
file-filters: []

variables:
  # source: your-source-dir
  source: testdir
  state: .state.json
  cli: ccc.exe --config-path .cos.yaml
  bucket: 'cos://sdfs-1254063044'

commands:
  start-up: 
  clean-up: 
  download-state: $cli cp $bucket/$state $state
  upload-state: $cli cp "$apath" $bucket/$state
  delete-file: $cli rm "$bucket/$rpath" --force
  delete-dir: 
  upload-file: $cli cp "$apath" "$bucket/$rpath"
  making-dir: 